### ISSUE TITLE
Calls to API fail with 404 error

### ISSUE THREAD

**Issue by pmarflee** [ArmandJ77/VueCore#1]
I was interested in this project because I had been having some trouble getting a front-end app generated using the Vue CLI Webpack template to play nicely with a .NET Core backend.  However I wasn't able to get it to work properly.  If I run the web app from Visual Studio (F5), the web page loads but all the calls to the API back-end fail with a 404 error.  What do I need to do to get the web app to run correctly?

**Comment by ArmandJ77-zz** [comment]
thanks for you interest in the project and raising this issue. I suspect the issue may be as a result of the axios calls which are pointing to the incorrect port number when running as localhost. to resolve:

-> Run VS (F5) 
-> Then in the solution explorer navigate to VueCore -> src -> components -> clients
->  Update each component's axios base URLs to point to your local host which is currently running.

should this not work you could try (this resolved my issue when i pulled the project for investigation):

-> open the VueCore Properties -> debug -> update App Url => "http://localhost:8081" 
-> config -> index.js line 25 -> port:8081
-> Update axios base URL port numbers

Keep in mind that there is no hard dependency between .NET core and Vue.js and interaction between controllers and components are done through ajax calls.

This project is just aimed at proving the concept, if you are considering this approach for a production application I would recommend that the axios calls be extracted to their own architectural layer and have the baseURL read from an app setting. this would also make your CI/CD pipeline easier to maintain.
